# ==========================
#   STAGE 1: BUILD
# ==========================
FROM maven:3.9.9-eclipse-temurin-17-alpine AS builder

WORKDIR /workspace/app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src/ ./src/
RUN mvn clean package -DskipTests -B

# Download Datadog Java Tracer
RUN apk add --no-cache curl=8.12.1-r1 && \
    curl -sSL https://dtdg.co/latest-java-tracer -o /workspace/app/dd-java-agent.jar && \
    chmod 0444 /workspace/app/dd-java-agent.jar && \
    apk del curl


# ==========================
#   STAGE 2: RUNTIME
# ==========================
FROM amazoncorretto:17-alpine3.20

WORKDIR /app
RUN mkdir -p /app && chmod 0755 /app

COPY --from=builder /workspace/app/target/*.jar /app/app.jar
COPY --from=builder /workspace/app/dd-java-agent.jar /app/dd-java-agent.jar
RUN chmod 0444 /app/app.jar /app/dd-java-agent.jar

USER 1001

EXPOSE 8080
ENV JAVA_TOOL_OPTIONS="-Djava.io.tmpdir=/tmp"

ENTRYPOINT ["sh","-c","java -XX:+UseContainerSupport -XX:MaxRAMPercentage=${MAX_RAM_PERCENTAGE:-60.0} -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Duser.timezone=America/Mexico_City -javaagent:/app/dd-java-agent.jar -jar /app/app.jar"]

HEALTHCHECK --interval=30s --timeout=5s --start-period=30s \
  CMD wget --spider http://localhost:8080/api/voucher/status || exit 1